name: Build MacOS

on:
  workflow_dispatch:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-arm64:
    runs-on: macos-14

    defaults:
      run:
        working-directory: src

    steps:
    - uses: actions/checkout@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.2.3'
        arch: 'clang_64'

    - name: Change XCode Version
      run: sudo xcode-select --switch /Applications/Xcode_14.3.1.app

    - name: Re-install zlib
      run: brew install zlib

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Upload app
      uses: actions/upload-artifact@v4
      with:
        name: 'mac-build-arm64'
        path: '${{github.workspace}}/build/snorain-imager.app*'
        
  build-x86:
    runs-on: macos-13

    defaults:
      run:
        working-directory: src

    steps:
    - uses: actions/checkout@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v3

    - name: Change XCode Version
      run: sudo xcode-select --switch /Applications/Xcode_14.3.1.app

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Upload app
      uses: actions/upload-artifact@v4
      with:
        name: 'mac-build-x86'
        path: '${{github.workspace}}/build/snorain-imager.app*'
