name: Build Ubuntu .deb

on:
  workflow_dispatch:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Update apt
      run: sudo apt update -y
      
    - name: Install dependencies
      run: sudo apt install -y --no-install-recommends build-essential devscripts debhelper cmake git libarchive-dev libcurl4-gnutls-dev
           qtbase5-dev qtbase5-dev-tools qtdeclarative5-dev libqt5svg5-dev qttools5-dev libgnutls28-dev
           qml-module-qtquick2 qml-module-qtquick-controls2 qml-module-qtquick-layouts qml-module-qtquick-templates2 qml-module-qtquick-window2 qml-module-qtgraphicaleffects

    - name: Build
      run: debuild -uc -us

    - run: |
        ls -lah ../
        ls -lah *
        ls -lah ${{github.workspace}}

    - uses: actions/upload-artifact@v4
      with:
        name: 'ubuntu-build'
        path: |
          ${{github.workspace}}/*.deb
          ${{github.workspace}}/*.ddeb
